import '../global.css'

export const metadata = {
  title: 'Connect 360',
  // description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className='relative mobile:overflow-x-hidden'>{children}</body>
    </html>
  )
}
